
import Navbar from '@/Components/Navbar/page'
import Footer from '@/Components/Footer/page'
import StyledComponentsRegistry from '../../lib/registery.js'
import { Montserrat, Roboto, Poppins } from "next/font/google";
import "./globals.css"; // If using global styles


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const montserrat = Montserrat({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

// Load Roboto for body text
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

// Load Poppins for buttons
const poppins = Poppins({
  weight: ["500", "700"],
  subsets: ["latin"],
  display: "swap",
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${roboto.className} ${poppins.className}`}>
        <StyledComponentsRegistry>
          <Navbar />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
